apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: adservicehpa
spec:
  maxReplicas: 4
  minReplicas: 2
  scaleTargetRef:
    apiVersion: argoproj.io/v1alpha1
    kind: Rollout
    name: adservice
  targetCPUUtilizationPercentage: 80
