apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: frontendhpa
spec:
  maxReplicas: 6
  minReplicas: 2
  scaleTargetRef:
    apiVersion: argoproj.io/v1alpha1
    kind: Rollout
    name: frontend
  targetCPUUtilizationPercentage: 80
