apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: shippingservicehpa
spec:
  maxReplicas: 6
  minReplicas: 2
  scaleTargetRef:
    apiVersion: argoproj.io/v1alpha1
    kind: Rollout
    name: shippingservice
  targetCPUUtilizationPercentage: 80
